list(
  tar_target(FUNDIV_Plots_disturbance_belgium, 
             Get_disturbance_per_plot("belgium", 15, FUNDIV_tree,
                                      "data/Disturbance")), 
  tar_target(FUNDIV_Plots_disturbance_france, 
             Get_disturbance_per_plot("france", 15, FUNDIV_tree,
                                      "data/Disturbance")), 
  tar_target(FUNDIV_Plots_disturbance_germany, 
             Get_disturbance_per_plot("germany", 15, FUNDIV_tree,
                                      "data/Disturbance")), 
  tar_target(FUNDIV_Plots_disturbance_finland, 
             Get_disturbance_per_plot("finland", 15, FUNDIV_tree,
                                      "data/Disturbance")), 
  tar_target(FUNDIV_Plots_disturbance_sweden, 
             Get_disturbance_per_plot("sweden", 15, FUNDIV_tree,
                                      "data/Disturbance")), 
  tar_target(FUNDIV_Plots_disturbance_spain, 
             Get_disturbance_per_plot("spain", 50, FUNDIV_tree,
                                      "data/Disturbance"))
)
