list(
  tar_target(Map_areaCoveredPerDisturbance_FUNDIVplots, 
           Map_FUNDIVplots_areaCoveredPerDisturbance(FUNDIV_tree_disturbance100m)), 
  tar_target(plot_Compare_NFI_Senf_disturbance_area, 
           Compare_NFI_Senf_disturbance_area(FUNDIV_tree_disturbance100m, NFI_plot_remeasure)), 
  tar_target(plot_prevalence_per_country_per_year, 
           plot_annualPrevalence(prevalence_per_country_per_year)), 
  tar_target(plot_disturbedArea_perMortalityRate_15m, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance15m, 
                                                 "Buffer = 15m radius", 
                                                 death.in = "natural mortality")), 
  tar_target(plot_disturbedArea_perMortalityRate_100m, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance100m, 
                                                 "Buffer = 100m radius", 
                                                 death.in = "natural mortality")), 
  tar_target(plot_disturbedArea_perMortalityRate_200m, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance200m, 
                                                 "Buffer = 200m radius", 
                                                 death.in = "natural mortality")), 
  tar_target(plot_disturbedArea_perMortalityRate_200m_harvest, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance200m, "", 
                                                 death.in = "harvested")), 
  tar_target(plot_disturbedArea_perMortalityRate_200m_unknown, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance200m, "", 
                                                 death.in = "unknown cause")), 
  tar_target(plot_disturbedArea_perMortalityRate_200m_alldeath, 
           plot_areaDisturbance_perMortalityRate(FUNDIV_tree_disturbance200m, "", 
                                                 death.in = c("natural mortality", "harvested", "unknown cause"))), 
  tar_target(plot_compare_mortality_tree_plot_level, 
             plot_mortality_tree_plot(NFI_tree_alive_remeasure, NFI_plot_remeasure)),
  tar_target(plot_probability_to_be_harvested, 
             plot_harvest_probability(NFI_tree_alive_remeasure, NFI_plot_remeasure, NFI_tree_alive)),
  tar_target(plot_probability_to_be_harvested2, 
             plot_harvest_probability2(NFI_tree_alive_remeasure, NFI_plot_remeasure, NFI_tree_alive)), 
  tar_target(fig_status_disturbance, 
             plot_status_disturbance(NFI_tree, NFI_tree_remeasured, NFI_plot_remeasure, NFI_species)),
  tar_target(fig_convergence_simulated, plot_convergence(jags_simulated, "Simulated data - Dj latent")), 
  tar_target(fig_convergence_simulated_2, plot_convergence(jags_simulated_2, "Simulated data - Dj true data")), 
  tar_target(fig_compare_jags_simulated, plot_compare_jags_simulated(data_jags_generated, jags_simulated)), 
  tar_target(fig_compare_jags_simulated_2, plot_compare_jags_simulated(data_jags_generated_2, jags_simulated_2)), 
  tar_target(fig_corr_param, plot_corr_param(jags_simulated)), 
  tar_target(fig_corr_param2, plot_corr_param(jags_simulated_2))
)
