#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
#### SCRIPT INTRODUCTION ####
#
#' @name functions_plot.R  
#' @description R script containing all functions relative to data
#               visualisation
#
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#### Section 1 - Data exploration - FUNDIV / Disturbances ####
#' @description Functions to explore the relation between tree
#'              mortality (FUNDIV) and disturbances (Senf 2021)
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#' Map  FUNDIV plots area covered per disturbance
#' @description Create 3 maps of FUNDIV plots, one per type of disturbance
#' @param FUNDIV_tree_with_disturbance FUNDIV tree table with one column per disturbance type
#'                                          Generated by function add_disturbance_to_FUNDIV

Map_FUNDIVplots_areaCoveredPerDisturbance <- function(FUNDIV_tree_with_disturbance){
  # Create sf object from FUNDIV_tree_withdisturbance
  FUNDIV_tree_withdisturbance.in <- FUNDIV_tree_with_disturbance %>%
    dplyr::select(plotcode, longitude, latitude, disturbance.storm, disturbance.fire, disturbance.other) %>%
    rename(Storm = disturbance.storm, Fire = disturbance.fire, Other = disturbance.other) %>%
    distinct %>%
    gather(key = 'disturbance', value = "coverage", "Storm", "Fire", "Other") %>%
    mutate(disturbance = factor(disturbance, levels = c("Storm", "Fire", "Other")), 
           coverage = 100*coverage) %>%
    filter(!is.na(coverage)) %>%
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant")
  
  # Map the generated sf object
  ne_countries(scale = "medium", returnclass = "sf") %>%
    ggplot(aes(geometry = geometry)) +
    geom_sf(fill = "#E9ECEF", show.legend = F) +
    geom_sf(data = FUNDIV_tree_withdisturbance.in, 
            shape = 16, aes(color = coverage), 
            show.legend = "point", size = 0.2) +
    scale_color_gradient(low = "#CAF0F8", high = "#03045E", 
                         name = "% area affected") +
    coord_sf(expand = FALSE, xlim = c(-25, 40), ylim = c(35, 72)) + 
    annotation_scale(location = "bl", width_hint = 0.13) +
    annotation_north_arrow(location = "tl", which_north = "true", 
                           pad_x = unit(0.35, "in"), pad_y = unit(0.1, "in"),
                           style = north_arrow_fancy_orienteering) +
    facet_wrap(~ disturbance, nrow = 1)  +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_line(colour = 'lightgray', linetype = "dashed"),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold")) 
}




#' Compare disturbance NFI Senf Area
#' @description Function that plot  relation between the field estimation of 
#'              disturbance intensity in France, and the percentage of area covered 
#'              by each type of "Senf" disturbance.
#' @param FUNDIV_tree_with_disturbance FUNDIV tree table with disturbance data
#' @param NFI_plot_remeasure Table containing NFI plot data for remeasured plots

Compare_NFI_Senf_disturbance_area <- function(FUNDIV_tree_with_disturbance, 
                                              NFI_plot_remeasure){
  FUNDIV_tree_with_disturbance %>%
    dplyr::select(plotcode, disturbance.storm, 
                  disturbance.fire, disturbance.other) %>%
    distinct() %>%
    merge((NFI_plot_remeasure %>% mutate(plotcode = paste0(idp, "_FR"))), 
          by = "plotcode", all.x = T, all.y = F) %>%
    mutate(natureNFI = case_when(nincid5 == 1 ~ "Fire disturbance", 
                                 nincid5 == 3 ~ "Landslide disturbance", 
                                 nincid5 == 4 ~ "Storm disturbance", 
                                 nincid5 %in% c(2, 5) ~ "Other disturbance", 
                                 TRUE ~ "No disturbance"), 
           intensityNFI = case_when(incid5 == 0 ~ 0, 
                                    incid5 == 1 ~ 12.5, 
                                    incid5 == 2 ~ 37.5, 
                                    incid5 == 3 ~ 62.5, 
                                    incid5 == 4 ~ 87.5)) %>%
    dplyr::select(plotcode, disturbance.storm, 
                  disturbance.fire, disturbance.other, 
                  natureNFI, intensityNFI) %>%
    pivot_longer(c(disturbance.storm, 
                   disturbance.fire, disturbance.other), 
                 names_to = "Source", 
                 values_to = "Disturbance") %>%
    mutate(Disturbance = ifelse(is.na(Disturbance), 0, Disturbance)) %>%
    filter(!is.na(intensityNFI)) %>%
    mutate(Senf_type = sub(".+\\.", "", Source)) %>%
    group_by(natureNFI, intensityNFI, Senf_type) %>%
    mutate(label = paste0("(", n(), ")")) %>%
    ungroup() %>%
    mutate(Disturbance = 100*Disturbance) %>%
    filter(natureNFI %in% c("Fire disturbance", "Storm disturbance", 
                            "Other disturbance")) %>%
    ggplot(aes(x = intensityNFI, y = Disturbance, colour = Senf_type, 
               group = interaction(Senf_type, intensityNFI))) + 
    geom_boxplot(outlier.alpha = 0.5) + 
    facet_wrap(~ natureNFI) + 
    geom_text(aes(label = label, y = 110), inherit.aes = T, 
              colour = 'black', size = 4) + 
    xlab(expression(atop("Disturbance intensity (%)", 
                         italic("(NFI field estimation)")))) + 
    ylab(expression(atop("% plot area covered by disturbance", 
                         italic("(Senf estimation)")))) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold")) + 
    scale_color_manual(values = c("#F4A259", "#8CB369", "#5B8E7D"))
}



#' Plot disturbed area per mortality rate
#' @description Function that classify NFI plots per mortality rate, and that plot
#'              for each mortality rate class the % of area covered by each type 
#'              of "Senf" disturbance.
#' @param FUNDIV_tree_disturbance FUNDIV tree table with disturbance data
#' @param title.in Character : title of the plot (useful to specify the buffer)
#' @param death.in character vector, indicating which status is considered a dead tree 
#'                 Possible choices: "natural mortality", "harvested", "unknown cause"

plot_areaDisturbance_perMortalityRate <- function(FUNDIV_tree_disturbance, title.in, death.in){
  # Identify the status corresponding to death modes. 
  death.status.in <- data.frame(tree.status = c(4, 3, 5), 
                                death = c("natural mortality", "harvested", "unknown cause"))
  this.status.in <- death.status.in$tree.status[which(death.status.in$death %in% death.in)]
  
  # Make the plot
  FUNDIV_tree_disturbance %>%
    # Remove death status not in death.in, and recruits (2)
    filter(treestatus_th %in% c(2, this.status.in)) %>%
    # Compute mortality per plot
    mutate(death.count = case_when(treestatus_th %in% this.status.in ~ 1, TRUE ~ 0)) %>%
    dplyr::select(plotcode, death.count, disturbance.fire, disturbance.storm, disturbance.other) %>%
    replace_na(replace = list(disturbance.fire = 0, 
                              disturbance.storm = 0, 
                              disturbance.other = 0)) %>%
    group_by(plotcode) %>%
    summarize(death.prop = round(sum(death.count)/n()*100, digits = 0), 
              fire.prop = sum(disturbance.fire)/n()*100, 
              storm.prop = sum(disturbance.storm)/n()*100, 
              other.prop = sum(disturbance.other)/n()*100) %>%
    mutate(death.prop.category = case_when(death.prop == 0 ~ "0%", 
                                           death.prop %in% c(1:10) ~ "1 - 10%", 
                                           death.prop %in% c(11:20) ~ "11 - 20%", 
                                           death.prop %in% c(21:30) ~ "21 - 30%", 
                                           death.prop %in% c(31:40) ~ "31 - 40%", 
                                           death.prop %in% c(41:50) ~ "41 - 50%", 
                                           death.prop %in% c(51:60) ~ "51 - 60%", 
                                           death.prop %in% c(61:70) ~ "61 - 70%", 
                                           death.prop %in% c(71:80) ~ "71 - 80%", 
                                           death.prop %in% c(81:90) ~ "81 - 90%", 
                                           death.prop %in% c(91:100) ~ "91 - 100%"), 
           undisturbed.prop = 100 - (fire.prop + storm.prop + other.prop)) %>%
    group_by(death.prop.category) %>%
    summarise(Fire = sum(fire.prop)/n(), 
              Storm = sum(storm.prop)/n(), 
              Other = sum(other.prop)/n(), 
              Undisturbed = sum(undisturbed.prop)/n(), 
              label = paste0("(", n(), ")"), 
              label.pos = 105) %>%
    gather(key = "Disturbance", value = "Area.percentage", "Fire", "Storm", "Other", "Undisturbed") %>%
    ggplot(aes(x = death.prop.category, y = Area.percentage, fill = Disturbance)) + 
    geom_bar(stat = "identity") + 
    geom_text(aes(y = label.pos, label= label), vjust=-0.2, size=2.5, inherit.aes = T) + 
    scale_fill_manual(values = c("#F4A259", "#8CB369", "#5B8E7D", "#E0E1DD")) +
    xlab(paste0("Mortality rate (%) based on ", 
                paste(death.in, collapse = " + "))) + 
    ylab("Global Disturbance Regime") +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text.y = element_text(size = 11), 
          axis.text.x = element_text(size = 10, angle = 30, vjust = 1, hjust = 1), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank()) + 
    ggtitle(title.in)
}



#' Plot Annual prevalence 
#' @description Function that the annual prevalence (%) of Senf disturbance
#'              per country and per year, along with the period covered by FUNDIV census
#' @param data_annualPrevalence A list with two df: @data.plot contains the prevalence (in %) 
#'                              per country, year and disturbance and @country.date contains 
#'                              the year of the oldest 1st census, and most recent 2nd census 
#'                              per country
plot_annualPrevalence <- function(data_annualPrevalence){
  
  data_annualPrevalence$data.plot %>%
    ggplot(aes(x = year, y = Prevalence, color = disturbance.type, group = disturbance.type)) + 
    geom_line(size = 1) + 
    facet_wrap(~ Country, nrow = 2) + 
    scale_colour_manual(values = c("#F4A259", "#8CB369", "#5B8E7D")) +
    geom_vline(data = data_annualPrevalence$country.date, 
               aes(xintercept = Year), linetype = "dashed")+
    xlab("Year") + ylab("Annual prevalence (%)") +
    scale_x_continuous(breaks = c(199:202)*10) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, hjust = 0))
}

#' plot agreste against disturbance
#' @description Function to plot salvage logging in France against prevalence of storm and fire
#' @param annual_prevalence list containing as first element a dataframe with prevalence per country and per year
#' @param data_agreste Agreste data on salvage logging annual volumes in France
#' @return a ggplot object
plot_agreste_disturbance <- function(annual_prevalence.in, data_agreste.in){
  # Plot salvage logging volumes
  out.plot.a <- data_agreste.in %>%
    ggplot(aes(x = year, y = Volume, group = Use, colour = Use)) + 
    geom_line(size = 1) + 
    xlab("") + ylab(expression(atop("Volume "("m"^3)))) + 
    scale_x_continuous(breaks = c(2009, 2012, 2015, 2018)) + 
    scale_color_manual(values = c("#6A994E", "#8D99AE", "#936639", "#D62828")) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(), 
          legend.position = c(0.8, 0.7), 
          legend.key = element_rect(fill = alpha("white", 0.0))) 
  
  # Plot prevalence of storm and fire in france from 2009 to 2019
  out.plot.b <- annual_prevalence.in$data.plot %>%
    filter(year %in% c(2009:2019), Country == "France", 
           disturbance.type %in% c("Fire", "Storm")) %>%
    ggplot(aes(x = year, y = Prevalence, color = disturbance.type, group = disturbance.type)) + 
    geom_line(size = 1) + 
    scale_colour_manual(values = c("#F4A259", "#5B8E7D")) +
    ylab(expression(atop("Annual prevalence", "in France (%)"))) + xlab("") +
    scale_x_continuous(breaks = c(2009, 2012, 2015, 2018)) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(), 
          legend.position = c(0.8, 0.8), 
          legend.key = element_rect(fill = alpha("white", 0.0))) 
  
  # Merge the two plots
  plot_grid(out.plot.a, out.plot.b, nrow = 2, 
            labels = c("(a)", "(b)"), align = "v")
}



#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#### Section 2 - Data Analysis - FUNDIV / Disturbances ####
#' @description Functions to analyse the relation between tree
#'              mortality (FUNDIV) and disturbances (Senf 2021)
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



#' Plot mortality tree and plot level - French NFI
#' @description Function to compare disturbance-related mortality estimated by NFI agents in France at the plot level
#'              with tree level mortality, computed with and without the harvest rate. 
#' @param NFI_tree_alive_remeasure Table of census 2 data at tree level, for trees that were alive at census 1
#' @param NFI_plot_remeasure Table of census 2 data at plot level
plot_mortality_tree_plot <- function(NFI_tree_alive_remeasure, NFI_plot_remeasure){
  data.plot.in <- NFI_tree_alive_remeasure %>%
    filter(!(veget5 %in% c("N", "T"))) %>%
    mutate(alive = case_when(veget5 %in% c("0") ~ 1, TRUE ~ 0), 
           dead = case_when(veget5 %in% c("M", "A", "1", "2") ~ 1, TRUE ~ 0),
           harvested = case_when(veget5 %in% c("6", "7") ~ 1, TRUE ~ 0)) %>%
    group_by(idp) %>%
    summarise(death.rate = sum(dead, na.rm = T)/n()*100,
              alive.rate = sum(alive, na.rm = T)/n()*100,
              harvest.rate = sum(harvested, na.rm = T)/n()*100) %>%
    merge(NFI_plot_remeasure, by = "idp", all.x = T, all.y = F) %>%
    filter(!is.na(year))
  
  data.plot.in %>% 
    mutate(disturbance_intensity = case_when(incid5 == 0 ~ "0%", 
                                             incid5 == 1 ~ "1% - 25%", 
                                             incid5 == 2 ~ "25% - 50%", 
                                             incid5 == 3 ~ "50% - 75%", 
                                             incid5 == 4 ~ "75% - 100%"), 
           deathAndHarvest.rate = harvest.rate + death.rate) %>%
    filter(!(is.na(disturbance_intensity))) %>%
    gather(key = "rate.method", value = "rate", "deathAndHarvest.rate", "death.rate") %>%
    mutate(rate.method = case_when(rate.method == "death.rate" ~ "Mortality only", 
                                   rate.method == "deathAndHarvest.rate" ~ "Mortality and harvest")) %>%
    ggplot(aes(x = disturbance_intensity, y = rate)) + 
    geom_boxplot(fill = "lightgray") + 
    facet_wrap(~ rate.method) + 
    xlab("Disturbance intensity (NFI estimation)") + 
    ylab("Mortality rate from tree data") +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold")) + 
    geom_hline(yintercept = c(25, 50, 75), linetype = "dashed", colour = "red")
}



#' Plot harvest probability
#' @description Function to plot a modeled probability to be harvested as a function
#'              of dbh, and of whether the tree was alive, or dead (due to different causes)
#' @param NFI_tree_alive_remeasure Table of census 2 data at tree level, for trees that were alive at census 1
#' @param NFI_plot_remeasure Table of census 2 data at plot level
#' @param NFI_tree_alive Table containing data of census 1 and 2 for trees that were alive at census 1
plot_harvest_probability <- function(NFI_tree_alive_remeasure, NFI_plot_remeasure, 
                                     NFI_tree_alive){
  # Format data at tree level
  data.tree.in <- NFI_tree_alive_remeasure %>%
    merge(NFI_plot_remeasure, by = "idp", all.x = T, all.y = F) %>%
    # Remove lost trees
    filter(!(veget5 %in% c("N", "T"))) %>%
    # Remove unknown years
    filter(!is.na(year)) %>%
    # Remove all alive trees
    filter(veget5 != "0") %>%
    # Remove unknown incident 
    filter(!(is.na(nincid5))) %>%
    # create status and harvest column
    mutate(status = case_when(nincid5 == 0 ~ "Undisturbed plots", 
                              nincid5 == 1 ~ "Fire-disturbed plots", 
                              nincid5 == 4 ~ "Storm-disturbed plots", 
                              nincid5 %in% c(2, 3, 5) ~ "Other disturbances"), 
           harvest = case_when(veget5 %in% c("6", "7") ~ 1, 
                               veget5 %in% c("0", "M", "A", "1", "2") ~ 0), 
           idt = paste0(idp, "_", a)) %>%
    # add dbh at census1
    merge((NFI_tree_alive %>% mutate(idt = paste0(idp, "_", a)) %>% dplyr::select(idt, c13)), 
          by = "idt", all.x = T, all.y = F) %>%
    mutate(dbh = round(c13*10/pi, digits = 0)) %>%
    dplyr::select(idp, idt, dbh, year, status, harvest, incid5)
  
  # harvest model
  model.in = glm(harvest ~ dbh*status + status*incid5, 
                 data = data.tree.in, 
                 family = binomial(link = "logit"))
  newdata.in <- expand.grid(dbh = c(100:1500), 
                            status = unique(data.tree.in$status), 
                            incid5 = unique(data.tree.in$incid5)) %>%
    filter(!(is.na(incid5))) %>%
    filter(!(incid5 == 0 & status != "Undisturbed plots")) %>%
    filter(!(incid5 > 0 & status == "Undisturbed plots"))
  
  # Add prediction and confidence interval
  model.in.linkFunction <- family(model.in)$linkinv
  
  newdata.in <- bind_cols(newdata.in, setNames(as_tibble(predict(model.in, newdata.in, se.fit = TRUE)[1:2]),
                                               c('fit_link','se_link')))
  newdata.in <- mutate(newdata.in,
                       fit_resp  = model.in.linkFunction(fit_link),
                       right_upr = model.in.linkFunction(fit_link + (se_link)),
                       right_lwr = model.in.linkFunction(fit_link - (se_link)))
  
  # plot data
  newdata.in %>%
    mutate(disturbance_intensity = case_when(incid5 == 0 ~ "0%", 
                                             incid5 == 1 ~ "1% - 25%", 
                                             incid5 == 2 ~ "25% - 50%", 
                                             incid5 == 3 ~ "50% - 75%", 
                                             incid5 == 4 ~ "75% - 100%"))  %>%
    ggplot(aes(x = dbh, y = fit_resp, group = disturbance_intensity)) + 
    geom_line(size = 1, aes(colour = disturbance_intensity)) + 
    geom_ribbon(aes(ymin = right_lwr, ymax = right_upr, fill = disturbance_intensity), 
                alpha = 0.2) +
    facet_wrap(~ status) +
    ylim(0, 1) + 
    xlab("DBH (mm)") + ylab("Harvest probability") + 
    scale_color_manual(values = c("#F8BB49", "#F6AA1C", "#D97212", "#BC3908", "#A82A0A")) +
    scale_fill_manual(values = c("#F8BB49", "#F6AA1C", "#D97212", "#BC3908", "#A82A0A")) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_text(size = 12), 
          legend.key = element_rect(fill = alpha("white", 0.0)),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold"))
}




#' Plot harvest probability
#' @description Function to plot a modeled probability to be harvested as a function
#'              of dbh, and of whether the tree was alive, or dead (due to different causes)
#' @param NFI_tree_alive_remeasure Table of census 2 data at tree level, for trees that were alive at census 1
#' @param NFI_plot_remeasure Table of census 2 data at plot level
#' @param NFI_tree_alive Table containing data of census 1 and 2 for trees that were alive at census 1
plot_harvest_probability2 <- function(NFI_tree_alive_remeasure, NFI_plot_remeasure, 
                                     NFI_tree_alive){
  # Format data at tree level
  data.tree.in <- NFI_tree_alive_remeasure %>%
    merge(NFI_plot_remeasure, by = "idp", all.x = T, all.y = F) %>%
    # Remove lost trees
    filter(!(veget5 %in% c("N", "T"))) %>%
    # Remove unknown years
    filter(!is.na(year)) %>%
    # Remove all alive trees
    filter(veget5 != "0") %>%
    # Remove unknown incident 
    filter(!(is.na(nincid5))) %>%
    # create status and harvest column
    mutate(status = case_when(nincid5 == 0 ~ "Undisturbed plots", 
                              nincid5 == 1 ~ "Fire-disturbed plots", 
                              nincid5 == 4 ~ "Storm-disturbed plots", 
                              nincid5 %in% c(2, 3, 5) ~ "Other disturbances"), 
           harvest = case_when(veget5 %in% c("6", "7") ~ 1, 
                               veget5 %in% c("0", "M", "A", "1", "2") ~ 0), 
           idt = paste0(idp, "_", a)) %>%
    # add dbh at census1
    merge((NFI_tree_alive %>% mutate(idt = paste0(idp, "_", a)) %>% dplyr::select(idt, c13)), 
          by = "idt", all.x = T, all.y = F) %>%
    mutate(dbh = round(c13*10/pi, digits = 0)) %>%
    dplyr::select(idp, idt, dbh, year, status, harvest, incid5)
  
  # harvest model
  model.in = glm(harvest ~ dbh*status + status*incid5, 
                 data = data.tree.in, 
                 family = binomial(link = "logit"))
  newdata.in <- expand.grid(dbh = c(100:1500), 
                            status = unique(data.tree.in$status), 
                            incid5 = unique(data.tree.in$incid5)) %>%
    filter(!(is.na(incid5))) %>%
    filter(!(incid5 == 0 & status != "Undisturbed plots")) %>%
    filter(!(incid5 > 0 & status == "Undisturbed plots")) 
  
  # Add prediction and confidence interval
  model.in.linkFunction <- family(model.in)$linkinv
  
  newdata.in <- bind_cols(newdata.in, setNames(as_tibble(predict(model.in, newdata.in, se.fit = TRUE)[1:2]),
                                               c('fit_link','se_link')))
  newdata.in <- mutate(newdata.in,
                       fit_resp  = model.in.linkFunction(fit_link),
                       right_upr = model.in.linkFunction(fit_link + (se_link)),
                       right_lwr = model.in.linkFunction(fit_link - (se_link)))
  
  # plot data
  subset(newdata.in, status != "Undisturbed plots") %>%
    mutate(disturbance_intensity = case_when(incid5 == 0 ~ "0%", 
                                             incid5 == 1 ~ "1% - 25%", 
                                             incid5 == 2 ~ "25% - 50%", 
                                             incid5 == 3 ~ "50% - 75%", 
                                             incid5 == 4 ~ "75% - 100%"))  %>%
    ggplot(aes(x = dbh, y = fit_resp, group = disturbance_intensity)) + 
    geom_line(size = 1, aes(colour = disturbance_intensity)) + 
    geom_ribbon(aes(ymin = right_lwr, ymax = right_upr, fill = disturbance_intensity), 
                alpha = 0.2) +
    facet_wrap(~ status, nrow = 1) +
    ylim(0, 1) + 
    xlab("DBH (mm)") + ylab("Harvest probability") + 
    scale_color_manual(values = c("#F8BB49", "#F6AA1C", "#D97212", "#BC3908", "#A82A0A")) +
    scale_fill_manual(values = c("#F8BB49", "#F6AA1C", "#D97212", "#BC3908", "#A82A0A")) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_text(size = 12), 
          legend.key = element_rect(fill = alpha("white", 0.0)),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold"))
}





#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#### Section 3 - Model outputs and diagnostic - Bayesian mortality model ####
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#' Plot parameters value of a rjags object
#' @param fit.rjags.in rjags object
#' @param title.in plot title
plot_parameters <- function(fit.rjags.in, title.in = ""){
  as.data.frame(fit.rjags.in$BUGSoutput$sims.matrix) %>%
    dplyr::select(-deviance) %>%
    gather(key = "parameter", value = "value") %>%
    ggplot(aes(x = value)) + 
    geom_histogram(colour = "black") + 
    facet_wrap(~ parameter) + 
    geom_vline(xintercept = 0, linetype = "dashed") +
    xlab("Parameter value") +
    theme_bw() + 
    ggtitle(title.in)
}


#' Plot Markov chain convergence of a rjags object
#' @param fit.rjags.in rjags object
#' @param title.in plot title
plot_convergence <- function(fit.rjags.in, title.in = ""){
  ggs(as.mcmc(fit.rjags.in)) %>%
    filter(Parameter != "deviance") %>%
    mutate(Chain = as.factor(Chain)) %>%
    ggplot(aes(x = Iteration, y = value, colour = Chain, group = Chain)) + 
    geom_line() + 
    facet_wrap(~ Parameter, scales = "free") + 
    scale_color_manual(values = c("#335C67", "#E09F3E", "#9E2A2B")) +
    theme_bw() + 
    ggtitle(title.in) 
}


#' Function to compare the parameters true value and estimation by the bayesian model
#' @param data_jags_generated simulated data fot the bayesian model
#' @param jags_simulated output of the model fitted with data_jags_generated
plot_compare_jags_simulated <- function(data_jags_generated, jags_simulated){
  fitted.paramater.in <- as.data.frame(jags_simulated$BUGSoutput$sims.matrix) %>%
    dplyr::select(-deviance) %>%
    gather(key = "parameter", value = "value") %>%
    mutate(source = "Fitted value")
  
  for(i in 1:length(names(data_jags_generated$parameters))){
    true.paramater.in_i <- data.frame(
      parameter = names(data_jags_generated$parameters)[i], 
      value = data_jags_generated$parameters[[i]], 
      source = "True value")
    if(i == 1) true.paramater.in <- true.paramater.in_i
    else true.paramater.in <- rbind(true.paramater.in, true.paramater.in_i)
  }
  
  rbind(fitted.paramater.in, true.paramater.in) %>%
    ggplot(aes(x = value)) + 
    geom_histogram(colour = "black") + 
    facet_grid(source ~ parameter, scales = "free") + 
    geom_vline(xintercept = 0, linetype = "dashed") +
    xlab("Parameter value") +
    theme_bw()
}

