#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#
#### SCRIPT INTRODUCTION ####
#
#' @name functions_plot.R  
#' @description R script containing all functions relative to data
#               visualisation
#
#
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#### Section 1 - Data exploration - FUNDIV / Disturbances ####
#' @description Functions to explore the relation between tree
#'              mortality (FUNDIV) and disturbances (Senf 2021)
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


#' Map  FUNDIV plots area covered per disturbance
#' @description Create 3 maps of FUNDIV plots, one per type of disturbance
#' @param FUNDIV_tree_with_disturbance FUNDIV tree table with one column per disturbance type
#'                                          Generated by function add_disturbance_to_FUNDIV

Map_FUNDIVplots_areaCoveredPerDisturbance <- function(FUNDIV_tree_with_disturbance){
  # Create sf object from FUNDIV_tree_withdisturbance
  FUNDIV_tree_withdisturbance.in <- FUNDIV_tree_with_disturbance %>%
    dplyr::select(plotcode, longitude, latitude, disturbance.storm, disturbance.fire, disturbance.other) %>%
    rename(Storm = disturbance.storm, Fire = disturbance.fire, Other = disturbance.other) %>%
    distinct %>%
    gather(key = 'disturbance', value = "coverage", "Storm", "Fire", "Other") %>%
    mutate(disturbance = factor(disturbance, levels = c("Storm", "Fire", "Other")), 
           coverage = 100*coverage) %>%
    filter(!is.na(coverage)) %>%
    st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant")
  
  # Map the generated sf object
  ne_countries(scale = "medium", returnclass = "sf") %>%
    ggplot(aes(geometry = geometry)) +
    geom_sf(fill = "#E9ECEF", show.legend = F) +
    geom_sf(data = FUNDIV_tree_withdisturbance.in, 
            shape = 16, aes(color = coverage), 
            show.legend = "point", size = 0.2) +
    scale_color_gradient(low = "#CAF0F8", high = "#03045E", 
                         name = "% area affected") +
    coord_sf(expand = FALSE, xlim = c(-25, 40), ylim = c(35, 72)) + 
    annotation_scale(location = "bl", width_hint = 0.13) +
    annotation_north_arrow(location = "tl", which_north = "true", 
                           pad_x = unit(0.35, "in"), pad_y = unit(0.1, "in"),
                           style = north_arrow_fancy_orienteering) +
    facet_wrap(~ disturbance, nrow = 1)  +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_line(colour = 'lightgray', linetype = "dashed"),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold")) 
}




#' Compare disturbance NFI Senf Area
#' @description Function that plot  relation between the field estimation of 
#'              disturbance intensity in France, and the percentage of area covered 
#'              by each type of "Senf" disturbance.
#' @param FUNDIV_tree_with_disturbance FUNDIV tree table with disturbance data
#' @param NFI_plot_remeasure Table containing NFI plot data for remeasured plots

Compare_NFI_Senf_disturbance_area <- function(FUNDIV_tree_with_disturbance, 
                                              NFI_plot_remeasure){
  FUNDIV_tree_with_disturbance %>%
    dplyr::select(plotcode, disturbance.storm, 
                  disturbance.fire, disturbance.other) %>%
    distinct() %>%
    merge((NFI_plot_remeasure %>% mutate(plotcode = paste0(idp, "_FR"))), 
          by = "plotcode", all.x = T, all.y = F) %>%
    mutate(natureNFI = case_when(nincid5 == 1 ~ "Fire disturbance", 
                                 nincid5 == 3 ~ "Landslide disturbance", 
                                 nincid5 == 4 ~ "Storm disturbance", 
                                 nincid5 %in% c(2, 5) ~ "Other disturbance", 
                                 TRUE ~ "No disturbance"), 
           intensityNFI = case_when(incid5 == 0 ~ 0, 
                                    incid5 == 1 ~ 12.5, 
                                    incid5 == 2 ~ 37.5, 
                                    incid5 == 3 ~ 62.5, 
                                    incid5 == 4 ~ 87.5)) %>%
    dplyr::select(plotcode, disturbance.storm, 
                  disturbance.fire, disturbance.other, 
                  natureNFI, intensityNFI) %>%
    pivot_longer(c(disturbance.storm, 
                   disturbance.fire, disturbance.other), 
                 names_to = "Source", 
                 values_to = "Disturbance") %>%
    mutate(Disturbance = ifelse(is.na(Disturbance), 0, Disturbance)) %>%
    filter(!is.na(intensityNFI)) %>%
    mutate(Senf_type = sub(".+\\.", "", Source)) %>%
    group_by(natureNFI, intensityNFI, Senf_type) %>%
    mutate(label = paste0("(", n(), ")")) %>%
    ungroup() %>%
    mutate(Disturbance = 100*Disturbance) %>%
    filter(natureNFI %in% c("Fire disturbance", "Storm disturbance", 
                            "Other disturbance")) %>%
    ggplot(aes(x = intensityNFI, y = Disturbance, colour = Senf_type, 
               group = interaction(Senf_type, intensityNFI))) + 
    geom_boxplot(outlier.alpha = 0.5) + 
    facet_wrap(~ natureNFI) + 
    geom_text(aes(label = label, y = 110), inherit.aes = T, 
              colour = 'black', size = 4) + 
    xlab(expression(atop("Disturbance intensity (%)", 
                         italic("(NFI field estimation)")))) + 
    ylab(expression(atop("% plot area covered by disturbance", 
                         italic("(Senf estimation)")))) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, face = "bold")) + 
    scale_color_manual(values = c("#F4A259", "#8CB369", "#5B8E7D"))
}



#' Plot disturbed area per mortality rate
#' @description Function that classify NFI plots per mortality rate, and that plot
#'              for each mortality rate class the % of area covered by each type 
#'              of "Senf" disturbance.
#' @param FUNDIV_tree_disturbance FUNDIV tree table with disturbance data
#' @param title.in Character : title of the plot (useful to specify the buffer)
#' @param death.in character vector, indicating which status is considered a dead tree 
#'                 Possible choices: "natural mortality", "harvested", "unknown cause"

plot_areaDisturbance_perMortalityRate <- function(FUNDIV_tree_disturbance, title.in, death.in){
  # Identify the status corresponding to death modes. 
  death.status.in <- data.frame(tree.status = c(4, 3, 5), 
                                death = c("natural mortality", "harvested", "unknown cause"))
  this.status.in <- death.status.in$tree.status[which(death.status.in$death %in% death.in)]
  
  # Make the plot
  FUNDIV_tree_disturbance %>%
    # Remove death status not in death.in, and recruits (2)
    filter(treestatus_th %in% c(2, this.status.in)) %>%
    # Compute mortality per plot
    mutate(death.count = case_when(treestatus_th %in% this.status.in ~ 1, TRUE ~ 0)) %>%
    dplyr::select(plotcode, death.count, disturbance.fire, disturbance.storm, disturbance.other) %>%
    replace_na(replace = list(disturbance.fire = 0, 
                              disturbance.storm = 0, 
                              disturbance.other = 0)) %>%
    group_by(plotcode) %>%
    summarize(death.prop = round(sum(death.count)/n()*100, digits = 0), 
              fire.prop = sum(disturbance.fire)/n()*100, 
              storm.prop = sum(disturbance.storm)/n()*100, 
              other.prop = sum(disturbance.other)/n()*100) %>%
    mutate(death.prop.category = case_when(death.prop == 0 ~ "0%", 
                                           death.prop %in% c(1:10) ~ "1 - 10%", 
                                           death.prop %in% c(11:20) ~ "11 - 20%", 
                                           death.prop %in% c(21:30) ~ "21 - 30%", 
                                           death.prop %in% c(31:40) ~ "31 - 40%", 
                                           death.prop %in% c(41:50) ~ "41 - 50%", 
                                           death.prop %in% c(51:60) ~ "51 - 60%", 
                                           death.prop %in% c(61:70) ~ "61 - 70%", 
                                           death.prop %in% c(71:80) ~ "71 - 80%", 
                                           death.prop %in% c(81:90) ~ "81 - 90%", 
                                           death.prop %in% c(91:100) ~ "91 - 100%"), 
           undisturbed.prop = 100 - (fire.prop + storm.prop + other.prop)) %>%
    group_by(death.prop.category) %>%
    summarise(Fire = sum(fire.prop)/n(), 
              Storm = sum(storm.prop)/n(), 
              Other = sum(other.prop)/n(), 
              Undisturbed = sum(undisturbed.prop)/n(), 
              label = paste0("(", n(), ")"), 
              label.pos = 105) %>%
    gather(key = "Disturbance", value = "Area.percentage", "Fire", "Storm", "Other", "Undisturbed") %>%
    ggplot(aes(x = death.prop.category, y = Area.percentage, fill = Disturbance)) + 
    geom_bar(stat = "identity") + 
    geom_text(aes(y = label.pos, label= label), vjust=-0.2, size=3.5, inherit.aes = T) + 
    scale_fill_manual(values = c("#F4A259", "#8CB369", "#5B8E7D", "#E0E1DD")) +
    xlab(paste0("Mortality rate (%) based on ", 
                paste(death.in, collapse = " + "))) + 
    ylab("% of the area affected") +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text.y = element_text(size = 11), 
          axis.text.x = element_text(size = 10, angle = 30, vjust = 1, hjust = 1), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank()) + 
    ggtitle(title.in)
}



#' Plot Annual prevalence 
#' @description Function that the annual prevalence (%) of Senf disturbance
#'              per country and per year, along with the period covered by FUNDIV census
#' @param data_annualPrevalence A list with two df: @data.plot contains the prevalence (in %) 
#'                              per country, year and disturbance and @country.date contains 
#'                              the year of the oldest 1st census, and most recent 2nd census 
#'                              per country
plot_annualPrevalence <- function(data_annualPrevalence){
  
  data_annualPrevalence$data.plot %>%
    ggplot(aes(x = year, y = Prevalence, color = disturbance.type, group = disturbance.type)) + 
    geom_line(size = 1) + 
    facet_wrap(~ Country, nrow = 2) + 
    scale_colour_manual(values = c("#F4A259", "#8CB369", "#5B8E7D")) +
    geom_vline(data = data_annualPrevalence$country.date, 
               aes(xintercept = Year), linetype = "dashed")+
    xlab("Year") + ylab("Annual prevalence (%)") +
    scale_x_continuous(breaks = c(199:202)*10) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(),
          strip.background = element_blank(), 
          strip.text = element_text(size = 12, hjust = 0))
}

#' plot agreste against disturbance
#' @description Function to plot salvage logging in France against prevalence of storm and fire
#' @param annual_prevalence list containing as first element a dataframe with prevalence per country and per year
#' @param data_agreste Agreste data on salvage logging annual volumes in France
#' @return a ggplot object
plot_agreste_disturbance <- function(annual_prevalence.in, data_agreste.in){
  # Plot salvage logging volumes
  out.plot.a <- data_agreste.in %>%
    ggplot(aes(x = year, y = Volume, group = Use, colour = Use)) + 
    geom_line(size = 1) + 
    xlab("") + ylab(expression(atop("Volume "("m"^3)))) + 
    scale_x_continuous(breaks = c(2009, 2012, 2015, 2018)) + 
    scale_color_manual(values = c("#6A994E", "#8D99AE", "#936639", "#D62828")) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(), 
          legend.position = c(0.8, 0.7), 
          legend.key = element_rect(fill = alpha("white", 0.0))) 
  
  # Plot prevalence of storm and fire in france from 2009 to 2019
  out.plot.b <- annual_prevalence.in$data.plot %>%
    filter(year %in% c(2009:2019), Country == "France", 
           disturbance.type %in% c("Fire", "Storm")) %>%
    ggplot(aes(x = year, y = Prevalence, color = disturbance.type, group = disturbance.type)) + 
    geom_line(size = 1) + 
    scale_colour_manual(values = c("#F4A259", "#5B8E7D")) +
    ylab(expression(atop("Annual prevalence", "in France (%)"))) + xlab("") +
    scale_x_continuous(breaks = c(2009, 2012, 2015, 2018)) +
    theme(panel.background = element_rect(color = 'black', fill = 'white'), 
          panel.grid = element_blank(),
          axis.text = element_text(size = 11), 
          axis.title = element_text(size = 13), 
          legend.text = element_text(size = 12), 
          legend.title = element_blank(), 
          legend.position = c(0.8, 0.8), 
          legend.key = element_rect(fill = alpha("white", 0.0))) 
  
  # Merge the two plots
  plot_grid(out.plot.a, out.plot.b, nrow = 2, 
            labels = c("(a)", "(b)"), align = "v")
}
